development:
  adapter: postgresql
  encoding: unicode
  database: geocoder_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: geocoder_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: geocoder_production
  pool: 5
  username: postgres
  password:
